%YAML 1.2
---
spring:
  application:
    name: opsporta-foobar
...
---
spring:
  profiles: c-dev4
ENV:
  BUNDLE_NAME: 'bundle.FOOBAR'
  PORT: 5000
  PUBLIC_URL: '/public'
  DEBUG_MODE: 'Off'
  ENVIRONMENT: 'dev'
  MAIL_OPTIONS_C: '{"userGroup":["opsportalfeedback@copart.com"],"from":"opsportal@copart.com","subject":"Ops-Portal Feedback","host":"msgsmtp.copart.com"}'
  BROADCAST_AUTHORIZED_IDS: 'OPSPORTUSR'
runConfig:
  mock: false
  companyCode: COPART
  AuthorizedIds:
    - OPSPORTUSR
  countryCode: US
  feedbackFAQLink: 'https://learning.copart.com/us/cas-portal-quick-reference-page/#h-5'
  stack: c
  enableDSI: true
  clientName: OPS
  isProd: false
  lockRefreshTime: 180000
  inactivityTime: 1800000
  autoTimeout: 120
  canadaYards:
    - 201
    - 202
    - 203
    - 204
    - 205
    - 206
    - 207
    - 276
    - 299
  FOOBAR:
    config: '/services/searchservice-ws/v1/opsPortal/FOOBAR/config'
...
---
spring:
  profiles: c-qa4
ENV:
  BUNDLE_NAME: 'bundle-FOOBAR'
  PORT: 3000
  PUBLIC_URL: '/public'
  DEBUG_MODE: 'Off'
  ENVIRONMENT: 'qa'
  MAIL_OPTIONS_C: '{"userGroup":["opsportalfeedback@copart.com"],"from":"opsportal@copart.com","subject":"Ops-Portal Feedback","host":"msgsmtp.copart.com"}'
  BROADCAST_AUTHORIZED_IDS: 'OPSPORTUSR'
runConfig:
  mock: false
  companyCode: COPART
  countryCode: US
  feedbackFAQLink: 'https://learning.copart.com/us/cas-portal-quick-reference-page/#h-5'
  stack: c
  enableDSI: true
  clientName: OPS
  isProd: false
  lockRefreshTime: 180000
  inactivityTime: 1800000
  autoTimeout: 120
  canadaYards:
    - 201
    - 202
    - 203
    - 204
    - 205
    - 206
    - 207
    - 276
    - 299
  FOOBAR:
    config: '/services/searchservice-ws/v1/opsPortal/FOOBAR/config'
...
---
spring:
  profiles: c-stg
ENV:
  BUNDLE_NAME: 'bundle-FOOBAR'
  PORT: 3000
  PUBLIC_URL: '/public'
  DEBUG_MODE: 'Off'
  ENVIRONMENT: 'stg'
  MAIL_OPTIONS_C: '{"userGroup":["opsportalfeedback@copart.com"],"from":"opsportal@copart.com","subject":"Ops-Portal Feedback","host":"msgsmtp.copart.com"}'
  BROADCAST_AUTHORIZED_IDS: 'OPSPORTUSR'
runConfig:
  mock: false
  companyCode: COPART
  countryCode: US
  feedbackFAQLink: 'https://learning.copart.com/us/cas-portal-quick-reference-page/#h-5'
  enableDSI: false
  stack: c
  clientName: OPS
  isProd: true
  lockRefreshTime: 180000
  inactivityTime: 1800000
  autoTimeout: 120
  canadaYards:
    - 201
    - 202
    - 203
    - 204
    - 205
    - 206
    - 207
    - 276
    - 299
  FOOBAR:
    config: '/services/searchservice-ws/v1/opsPortal/FOOBAR/config'
...
